import random
import json
from datetime import datetime

DAILY_VIBES = {
    "Monday": [
        "☕ 5-shot espresso",
        "📅 meetings that could have been emails",
        "😵‍💫 resolving merge conflicts from the weekend",
        "🧹 cleaning up technical debt",
        "🆕 starting a new branch",
        "🕯️ holding a seance for my motivation",
        "🪦 mourning the weekend",
        "🔋 recharging from Sunday scaries",
        "🗓️ 52 weeks of this",
        "🧊 frozen in the backlog",
    ],
    "Tuesday": [
        "🌮 taco tuesday",
        "2️⃣ two's day",
        "🤷 not Monday",
        "⏰ only Tuesday?",
        "💤 still recovering from Monday",
    ],
    "Wednesday": [
        "🐫 hump day",
        "🐪 halfway there",
        "📉 mid-week crisis",
        "🧗 climbing the mountain",
        "⚖️ perfectly balanced",
        "🌀 midweek vortex",
        "❓ is it Thursday yet",
        "🎢 over the hump",
    ],
    "Thursday": [
        "🔄 pre-friday refactor",
        "👀 reviewing PRs with one eye open",
        "🏃‍♂️ sprinting to the finish",
        "👁️ I can see Friday from here",
        "🏁 final lap energy",
        "🧹 pre-weekend cleanup",
        "🍷 Thursday is the new Friday",
    ],
    "Friday": [
        "🎉 deploy on friday",
        "🔥 production on fire",
        "🚫 read-only filesystem",
        "🍻 merging to main and leaving",
        "🚧 code freeze",
        "💃 disco mode",
        "📉 git push --force and pray",
        "🫡 deploying and disconnecting",
        "🎰 YOLO merge",
        "📵 do not disturb",
        "🏖️ mentally checked out",
        "🔥 future me's problem",
        "🪂 pushing to prod and jumping",
    ],
    "Saturday": [
        "🌞 touching grass",
        "🎮 side questing",
        "🛌 sleeping in",
        "🕹️ AFK",
        "🛠️ unnecessary side project",
        "🌿 lawn status: touched",
        "🍳 brunch debugging",
    ],
    "Sunday": [
        "😱 sunday scaries",
        "🗑️ garbage collection",
        "🧘 preparing the mental stack",
        "⏰ where did the weekend go",
    ]
}

GENERAL_VIBES = [
    "☕ 3-cups-of-coffee",
    "🍵 strictly matcha",
    "⚡ dangerously caffeinated",
    "🫗 running on empty",
    "🥤 iced coffee even in winter",
    "🍕 cold pizza for breakfast",
    "💧 staying hydrated (optional)",
    "🐛 'it's not a bug, it's a feature'",
    "😅 'works on my machine'",
    "🧹 git clean -fdx",
    "🧱 hitting a brick wall",
    "🧠 flow state",
    "📉 premature optimization",
    "🎨 CSS centering",
    "🏗️ infrastructure as worry",
    "🐍 pythonic",
    "🦀 rusting",
    "🗑️ deleting code is my passion",
    "🦆 talking to the rubber duck",
    "📑 reading documentation for fun",
    "🍝 spaghetti code sommelier",
    "🔍 regex wizardry",
    "😵 infinite recursion",
    "💊 taking the red pill",
    "🎹 mechanical keyboard ASMR",
    "🔬 git bisecting my life choices",
    "🧠 locked in",
    "🏗️ building the future",
    "🔨 smashing tickets",
    "📈 momentum building",
    "🎯 actually productive",
    "🪨 steady state",
    "🔧 deep work mode",
    "📝 documenting before I forget",
    "☁️ AWS console debugging",
    "⚛️ React hydration error",
    "🐳 Docker container",
    "🔐 sudo rm -rf",
    "🕸️ fighting the DOM",
    "📡 DNS propagation waiting room",
    "🧱 YAML indentation hell",
    "🐋 orchestrating containers",
    "🛡️ CORS policy violation",
    "🍪 clearing cookies",
    "🔌 turning it off and on again",
    "🧪 testing in production",
    "🧘 zen mode",
    "🌪️ chaotic good",
    "🌑 dark mode",
    "✨ main character energy",
    "🐢 slow and steady",
    "🐇 speed running production",
    "🦖 legacy code archaeologist",
    "🚀 ship it",
    "🫥 existing in the void",
    "🎭 imposter syndrome",
    "🧛 vampire coding hours",
    "🧟 zombie process",
    "🧙‍♂️ wizard",
    "🤺 fighting entropy",
    "💡 lightbulb moment",
    "🎧 noise-canceling headphones",
    "🎸 lo-fi beats to code to",
    "🔇 silence is golden",
    "🥁 heavy metal debugging",
    "🌧️ rainy day coding",
    "🔊 bass boosted",
    "🕹️ min-maxing productivity",
    "🎲 rolling a natural 1",
    "⚔️ dungeon master",
    "👾 8-bit aesthetic",
    "🌌 exploring the universe",
    "🤖 resisting the robot uprising",
    "🛰️ raster wrangling",
    "📍 spatial indexing everything",
    "🗺️ coordinate reference system crisis",
    "📐 GeoJSON geometry repair",
    "📊 staring at loss curves",
    "🤖 attention is all you need",
    "🔮 inference mode",
    "📉 overfitting to the vibes",
    "⚙️ first principles only",
    "🧮 understanding the math",
    "📖 reading the actual spec",
    "🚫 rejecting corporate buzzwords",
    "🔬 mechanically correct",
    "🫠 melting into the chair",
    "🦝 trash panda energy",
    "🐙 too many tabs open",
    "🌶️ spicy take incoming",
    "🦥 aggressive relaxation",
    "🎪 circus mode",
    "🧃 juice box and a nap",
    "🫧 living in a bubble",
    "🦴 running on fumes and spite",
    "🎠 same stuff different day",
    "🪤 trapped in a meeting",
    "🧲 attracting edge cases",
    "🎯 tunnel vision",
    "🌋 quietly seething",
    "🪩 unhinged but functional",
    "🦔 prickly but soft inside",
    "🧫 growing concerns",
    "🪦 RIP my PR",
    "📎 Clippy energy",
    "🗿 immutable",
    "🎰 random.random() < 0.5",
    "🦠 viral bug",
    "🏚️ haunted codebase",
    "🧊 frozen requirements.txt",
    "🔮 console.log debugging",
    "🦕 deprecated but still running",
    "🪬 code review protection spell",
    "🗡️ death by a thousand commits",
    "🧻 unrolling loops manually",
    "🎪 three-ring circus architecture",
    "🦴 bare metal",
    "🪤 honeypot endpoint",
    "🧊 cache invalidation",
    "🎲 nondeterministic test",
    "📿 hoping the CI passes",
    "🦎 10x lizard brain",
    "☢️ radioactive technical debt",
    "🏴‍☠️ pirating my own software",
    "🪖 production war room",
    "🦜 parroting best practices",
    "🧃 junior dev juice",
    "🪨 senior dev cynicism",
    "🎭 pretending to understand the requirements",
    "🧊 scope creep freezing",
    "🌊 drowning in JIRA tickets",
]

def get_vibe():
    day = datetime.today().strftime('%A')
    if day in DAILY_VIBES and random.random() < 0.25:
        return random.choice(DAILY_VIBES[day])
    return random.choice(GENERAL_VIBES)

def write_vibe_json(vibe):
    data = {
        "schemaVersion": 1,
        "label": "today's vibe",
        "message": vibe,
        "color": "blue"
    }
    with open("vibe.json", "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

if __name__ == "__main__":
    vibe = get_vibe()
    write_vibe_json(vibe)
