import random
import json
from datetime import datetime

DAILY_VIBES = {
    "Monday": [
        "5-shots of espresso (c)(c)(c)(c)(c)",
        "<<< meetings that could have been emails >>>",
        "resolving merge conflicts from the weekend (X_X)",
        "cleaning up technical debt",
        "starting a new branch",
        "holding a seance for my motivation",
        "mourning the weekend",
        "recharging from Sunday scaries",
        "52 weeks of this",
        "frozen in the backlog",
    ],
    "Tuesday": [
        "taco tuesday",
        "two's day",
        "not Monday ¯\\_(ツ)_/¯",
        "only Tuesday?",
        "still recovering from Monday (-_-)",
    ],
    "Wednesday": [
        "hump day",
        "[====----] week progress: 50%",
        "mid-week crisis",
        "/\\ climbing the mountain",
        "perfectly balanced",
        "midweek vortex (@)",
        "is it Thursday yet",
        "over the hump ^v^",
    ],
    "Thursday": [
        "pre-friday refactor",
        ">>> sprinting to the finish >>>",
        "I can see Friday from here",
        "pre-weekend cleanup",
        "Thursday is the new Friday",
    ],
    "Friday": [
        "deploy on friday \\o/",
        "~~~~ production on fire ~~~~",
        "hotfix Friday",
        "read-only filesystem",
        "merging to main and leaving",
        "*** code freeze ***",
        "disco mode",
        "git push --force and pray",
        "deploying and disconnecting o7",
        "<!> YOLO merge <!>",
        "do not disturb",
        "(...) mentally checked out",
        "future me's problem",
        "pushing to prod and jumping",
    ],
    "Saturday": [
        "touching grass",
        "side questing",
        "sleeping in (-.-)Zzz",
        "AFK",
        "building an unnecessary side project",
        "gone fishing ><>",
    ],
    "Sunday": [
        "sunday scaries (°□°)",
        "garbage collection",
        "(...) preparing the mental stack",
        "where did the weekend go?",
    ]
}

GENERAL_VIBES = [
    "3-cups-of-coffee (c)(c)(c)",
    "strictly matcha",
    "running on empty",
    "iced coffee even in winter",
    "cold pizza for breakfast",
    "staying hydrated",
    "it's not a bug, it's a feature",
    "works on my machine ¯\\_(ツ)_/¯",
    "git clean -fdx",
    "hitting a brick wall",
    "flow state (*_*)",
    "premature optimization",
    "CSS centering",
    "infrastructure as worry",
    "pythonic",
    "rusting",
    "deleting code is my passion",
    "/.+/ regex wizardry",
    "infinite recursion (@_@)",
    "taking the red pill",
    "locked in (⌐■_■) ",
    "actually productive",
    "steady state",
    "deep work mode",
    "documenting before I forget",
    "AWS console debugging",
    "React hydration error",
    "Docker container [ ]",
    "sudo rm -rf",
    "</> fighting the DOM </>",
    "DNS propagation waiting room (...)",
    "YAML indentation hell",
    "orchestrating containers",
    "CORS policy violation",
    "clearing cookies",
    "turning it off and on again",
    "testing in production",
    "zen mode (._.)",
    "chaotic good",
    "dark mode",
    "slow and steady (-_-)",
    ">>> speed running production >>>",
    "legacy code archaeologist",
    "--> ship it -->",
    "existing in the void ( )",
    "vampire coding hours",
    "zombie process (x.x)",
    "fighting entropy",
    "lightbulb moment",
    "silence is golden",
    "min-maxing productivity",
    "rolling a natural 1",
    "raster wrangling",
    "spatial indexing everything",
    "coordinate reference system crisis",
    "GeoJSON geometry repair",
    "staring at loss curves \\_/ ",
    "attention is all you need",
    "inference mode",
    "overfitting to the vibes \\o/",
    "first principles only",
    "understanding the math",
    "reading the actual spec",
    "rejecting corporate buzzwords",
    "mechanically correct",
    "melting into the chair (~.~)",
    "too many tabs open",
    "spicy take incoming",
    "aggressive relaxation",
    "circus mode",
    "juice box and a nap",
    "living in a bubble",
    "running on fumes and spite",
    "same stuff different day",
    "trapped in a meeting",
    "attracting edge cases",
    "tunnel vision",
    "quietly seething (>.<)",
    "unhinged but functional (^_^)",
    "prickly but soft inside",
    "growing concerns",
    "R.I.P my PR",
    "immutable",
    "[?] random.random() < 0.5",
    "viral bug",
    "haunted codebase",
    "frozen requirements.txt",
    "console.log debugging",
    "deprecated but still running",
    "code review protection spell",
    "---x death by a thousand commits",
    "unrolling loops manually",
    "three-ring circus architecture",
    "bare metal",
    "honeypot endpoint",
    "cache invalidation",
    "[?!] nondeterministic test",
    "(...) hoping the CI passes",
    "radioactive technical debt",
    "pirating my own software",
    "production war room",
    "parroting best practices",
    "junior dev juice",
    "senior dev cynicism",
    "pretending to understand the requirements (~_~)",
    "scope creep freezing",
    "drowning in JIRA tickets",
    "bug whisperer",
    "dependency hell",
    "database migration anxiety",
    "bikeshedding",
    "query optimization rabbit hole",
    "flaky tests",
    "/.*/ grepping the codebase",
    "off by one error",
    "race condition",
    "garbage collector",
    "projection confusion",
    "topology errors",
    "raster algebra",
    "global extent",
    "geocoding fails",
    "EPSG code lookup",
    "everything is fine",
    "velocity declining",
    "missing the point",
    "premature abstraction",
    "temporary permanent fix",
    "lost in the weeds",
    "negotiating with demons",
    "making users more compatible with their tools",
    "ensuring humans remain backward compatible",
    "mocking users for testing",
    "teaching users their requirements",
    "error 418: I'm a teapot",
    "user error between keyboard and chair",
    "NP-hard day",
    "buffer underflow",
]

def get_vibe():
    day = datetime.today().strftime('%A')
    if day in DAILY_VIBES and random.random() < 0.1:
        return random.choice(DAILY_VIBES[day])
    return random.choice(GENERAL_VIBES)

def write_vibe_json(vibe):
    data = {
        "schemaVersion": 1,
        "label": "Today's Vibe",
        "message": vibe,
        "color": "blue"
    }
    with open("vibe.json", "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

if __name__ == "__main__":
    vibe = get_vibe()
    write_vibe_json(vibe)
